controller_server:
  ros__parameters:
    controller_plugins: ["FollowPath"]
    FollowPath:
      plugin: "nav2_regulated_pure_pursuit_controller::RegulatedPurePursuitController"
      desired_linear_vel: 0.2
      lookahead_dist: 0.6
      min_lookahead_dist: 0.3
      max_lookahead_dist: 1.0
      max_angular_vel: 0.5
      rotate_to_heading_angular_vel: 0.5
      use_velocity_scaled_lookahead_dist: true
      # REQUIRED: Add transform tolerance
      transform_tolerance: 0.2  # Missing critical parameter!

planner_server:
  ros__parameters:
    expected_planner_frequency: 10.0
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_navfn_planner::NavfnPlanner"  # Fixed plugin name (:: instead of /)
      tolerance: 0.5
      # Optional but recommended for NavFn:
      use_astar: false  # Classic NavFn algorithm
      allow_unknown: true  # Allow planning through unknown space

costmap_2d:
  global_costmap:
    ros__parameters:
      footprint: "[[0.2, 0.2], [0.2, -0.2], [-0.2, -0.2], [-0.2, 0.2]]"
      resolution: 0.05
      # Remove robot_radius (conflicts with footprint)
      inflation_radius: 0.3
      plugins: ["static_layer", "obstacle_layer", "inflation_layer"]  # Added static_layer
      static_layer:
        map_topic: "map"  # Required for global costmap
        subscribe_to_updates: true
      obstacle_layer:
        enabled: true
        observation_sources: "scan"
        scan:
          topic: "scan"
          data_type: "LaserScan"  # Explicitly specify data type
          max_obstacle_height: 1.5
          obstacle_range: 3.0
          raytrace_range: 3.5
          clearing: true
      inflation_layer:
        enabled: true

  local_costmap:
    ros__parameters:
      footprint: "[[0.15, 0.15], [0.15, -0.15], [-0.15, -0.15], [-0.15, 0.15]]"
      resolution: 0.05
      # Remove robot_radius
      inflation_radius: 0.3
      plugins: ["obstacle_layer", "inflation_layer"]
      obstacle_layer:
        enabled: true
        observation_sources: "scan"
        scan:
          topic: "scan"
          data_type: "LaserScan"  # Add missing data type
          max_obstacle_height: 1.5
          obstacle_range: 3.0
          raytrace_range: 3.5
          clearing: true
      inflation_layer:
        enabled: true
      # Add local costmap specific parameters
      global_frame: odom  # Required for local costmap
      robot_base_frame: base_link
      rolling_window: true  # Enable rolling window mode
      width: 5.0  # Size of local costmap
      height: 5.0

bt_navigator:
  ros__parameters:
    default_bt_xml_filename: "navigate_w_replanning_and_recovery.xml"
    # Add frame IDs for clarity
    global_frame: map
    robot_base_frame: base_link

waypoint_follower:
  ros__parameters:
    # Fix incorrect plugin name
    waypoint_follower_plugin: "nav2_waypoint_follower::WaypointFollower"  # Correct namespace

amcl:
  ros__parameters:
    use_map_topic: false
    scan_topic: "scan"
    # Add basic AMCL parameters
    odom_frame_id: "odom"
    base_frame_id: "base_link"
    initial_pose_x: 0.0  # Recommended to set initial pose
    initial_pose_y: 0.0
    initial_pose_a: 0.0

map_server:
  ros__parameters:
    topic: "map"
    frame_id: "map"

world_model:
  ros__parameters:
    use_sim_time: true

localization_server:
  ros__parameters:
    use_sim_time: true
